git:
  commitPrefix:
    - pattern: '^feat/(\w+-\d+).*'
      replace: 'feat($1): âœ¨ '
    - pattern: '^fix/(\w+-\d+).*'
      replace: 'fix($1): ğŸ› '
    - pattern: '^test/(\w+-\d+).*'
      replace: 'test($1): ğŸ§ª '
    - pattern: '^chore/(\w+-\d+).*'
      replace: 'chore($1): ğŸ”§ '

